# Site
repository: valtoandre123/valtoandre123.github.io

# Personal info
name: Andre Valto
title: Physical Therapist
email: valtoandre123@gmail.com
website: https://valtoandre123.github.io

google_analytics: "UA-255934616-1"

# Dark Mode (true/false/never)
darkmode: true

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/andre.jpeg
about_content: | # this will include new lines to allow paragraphs
  My name is Andre Valto, I am a Physical Therapist and small business owner based out of Providence, Rhode Island.
  I am a father, dedicated business owner, new fisherman, and more! I enjoy sharing parts of my life online through social media
  as well as developing meaningful connections with my clients

  If you ever want to reach out to me, my email is provided on this page, thank you for visiting!



# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
